<?php $lookFor = $this->results->getUrlQuery()->isQuerySuppressed() ? '' : $this->params->getDisplayQuery(); ?>
<div id="contributors" class="col-sm-8">
    <h2 class="search-result-count">
        <span class="backToResults">
            <a href="<?=$this->url("search-results") . $this->results->getUrlQuery()->getParams(); ?>"><?= $this->transEsc('All results'); ?></a>
        </span>
        <?= number_format($this->pages->firstItemNumber, 0, ',', '.'); ?> -
        <?= number_format($this->pages->lastItemNumber, 0, ',', '.'); ?>
        <?= $this->transEsc('of'); ?>
        <?= number_format($this->pages->totalItemCount, 0, ',', '.'); ?>
        <?= $this->transEsc('for'); ?>
        <strong><?= $this->escapeHtml($lookFor); ?></strong>
    </h2>
    <h3 class="involvedPersons"><?=$this->transEsc('All persons involved')?></h3>
    <ul>
        <?php foreach ($this->paginator as $entry) : ?>
            <li>
                <a href="<?= $this->url('search-results').$this->results->getUrlQuery()->addFacet($this->contributorFacetKey, $entry['value'], $entry['operator']); ?>">
                    <?= $entry['displayText']?>
                </a>
                <span class="badge">
                    (<?= number_format($entry['count']); ?>)
                </span>
            </li>
        <?php endforeach; ?>
    </ul>
    <?=$this->paginationControl($this->paginator, 'Sliding', 'search/contributor-pagination.phtml', array('results' => $this->results, 'paginator' => $this->paginator))?>
</div>

<? /* Side facets */ ?>
<div id="facets" class="sidebar col-sm-4 hidden-print">
    <? foreach ($this->results->getRecommendations('side') as $current): ?>
        <?=$this->recommend($current)?>
    <? endforeach; ?>
</div>

<? /* Populate search */ ?>
<?php echo $this->partial(
    'search/setUpSearchFields.phtml',
    array('query' => $this->params->getQuery(), 'lookFor' => $lookFor)
); ?>