<? if ($this->pageCount): ?>
  <ul class="pagination">
    <? if (isset($this->previous)): ?>
      <li class="hidden-xs hidden-sm"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>">1</a></li>
      <li class="paging-label"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>

    <? if (count($this->pagesInRange) > 1): ?>
      <? foreach ($this->pagesInRange as $page): ?>
        <? if ($page != $this->current): ?>
          <li class="hidden-xs"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
        <? else: ?>
          <li class="active"><span><?=$page?></span></li>
        <? endif; ?>
      <? endforeach; ?>
    <? endif; ?>

    <? if (isset($this->next)): ?>
      <li class="paging-label"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><?=$this->transEsc('Next');?> &raquo;</a></li>
      <li class="hidden-xs hidden-sm"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>"><?=$this->pageCount?></a></li>
    <? endif; ?>
  </ul>
<? endif; ?>