<div class="span-5"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
    <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Find More')?></strong></p>
  <ul>
      <li><a href="<?=$this->url('topics/list')?>"><?=$this->transEsc('List of Subjects')?></a></li>
      <li><a href="<?=$this->url('topics')?>"><?=$this->transEsc('Tagcloud of Subjects')?></a></li>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('help-home', array(), array('query' => array('topic' => 'search')))?>" class="searchHelp"><?=$this->transEsc('Search Tips')?></a></li>
  </ul>
</div>
<div class="span-5 last"><p><strong><?=$this->transEsc('Service')?></strong></p>
    <ul>
        <li><a href="mailto:karin.aleksander@gender.hu-berlin.de?subject=[Vufind]"><?=$this->transEsc('Contact')?></a></li>
        <li><a href="https://www.gender.hu-berlin.de/impressum"><?=$this->transEsc('Imprint')?></a></li>
        <li><a href="http://www2.gender.hu-berlin.de/genderbib"><?=$this->transEsc('Weblog')?></a></li>
    </ul>
</div>
<div class="copyright">
    <ul>
        <li>&copy; ZtG 2014</li>
        <li>Zuletzt geändert: 29.06.2014</li>
        <li><a title="Powered by Vufind" href="http://vufind.org">Powered by Vufind</a></li>
    </ul>
</div>

<div class="share">
    <ul>
        <li>
            <a title="zur Facebookseite der Genderbibliothek" href="http://www.facebook.com/pages/Berlin-Germany/Genderbibliothek/33941646979" class="fb">
                <span class="hiddenStructure">zur Facebookseite der Genderbibliothek</span>
            </a>
        </li>
        <li>
            <a href="http://twitter.com/Genderbib" title="zum Twitteraccount der Genderbibliothek" class="tw">
                <span class="hiddenStructure">zum Twitteraccount der Genderbibliothek</span>
            </a>
        </li>
        <li>
            <a href="http://www.librarything.de/profile/genderbibliothek" title="zum LibraryThing Account der Genderbibliothek" class="librarything">
                <span class="hiddenStructure">zum LibraryThing Account der Genderbibliothek</span>
            </a>
        </li>
        <li>
            <a href="http://www.netvibes.com/genderbibliothek#General" title="zur Virtuellen Genderbibliothek" class="netvibes">
                <span class="hiddenStructure">zur Virtuellen Genderbibliothek</span>
            </a>
        </li>
        <li>
            <a href="http://flickr.com/photos/27910892@N07/" title="zum Flickr Fotostream der Genderbibliothek" class="flickr">
                <span class="hiddenStructure">zum Flickr Fotostream der Genderbibliothek</span>
            </a>
        </li>
        <li>
            <a title="Die RSS-Feeds der HU" href="http://www2.gender.hu-berlin.de/genderbib/feed/" class="rss">
                <span class="hiddenStructure">Die RSS-Feeds der HU</span>
            </a>
        </li>
    </ul>
</div>
<div class="clear"></div>
