<div class="span-5"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
    <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Find More')?></strong></p>
  <ul>
    <li><a href="#"><?=$this->transEsc('List of Subjects')?></a></li>
      <li><a href="#"><?=$this->transEsc('Tagcloud of Subjects')?></a></li>
    <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
    <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
    <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
    <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('help-home', array(), array('query' => array('topic' => 'search')))?>" class="searchHelp"><?=$this->transEsc('Search Tips')?></a></li>
    <li><a href="#"><?=$this->transEsc('Ask a Librarian')?></a></li>
    <li><a href="#"><?=$this->transEsc('FAQs')?></a></li>
  </ul>
</div>
<div class="span-5 last"><p><strong><?=$this->transEsc('Service')?></strong></p>
    <ul>
        <li><a href="#"><?=$this->transEsc('Contact')?></a></li>
        <li><a href="#"><?=$this->transEsc('Imprint')?></a></li>
        <li><a href="#"><?=$this->transEsc('Questions and Proposals')?></a></li>
        <li><a href="#"><?=$this->transEsc('Weblog')?></a></li>
    </ul>
</div>
<div class="copyright">
    <ul>
        <li>&copy; ZtG 2014</li>
        <li>Zuletzt geändert: 29.06.2014</li>
        <li><a href="#">Seite bearbeiten</a></li>
        <li>Powered by Vufind</li>
    </ul>
</div>
<div class="share">
    <ul>
        <li><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="Print" title="Print"></a></li>
        <li class="separate"><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="Mail" title="Mail"></a></li>
        <li><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="Facebook" title="Facebook"></a></li>
        <li><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="Twitter" title="Twitter"></a></li>
        <li><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="?" title="?"></a></li>
        <li><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="Sound" title="Sound"></a></li>
        <li class="last"><a href="#"><img src="<?=$this->imageLink('icons/placeholder_20x20.png')?>" alt="RSS" title="RSS"></a></li>
    </ul>
</div>
<div class="clear"></div>
