<div class="span-5"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
    <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Find More')?></strong></p>
  <ul>
      <li><a href="<?=$this->url('topics/list')?>"><?=$this->transEsc('List of Subjects')?></a></li>
      <li><a href="<?=$this->url('topics')?>"><?=$this->transEsc('Tagcloud of Subjects')?></a></li>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
  </ul>
</div>
<div class="span-5"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
  <ul>
    <li><a href="<?=$this->url('help-home', array(), array('query' => array('topic' => 'search')))?>" class="searchHelp"><?=$this->transEsc('Search Tips')?></a></li>
    <li><a href="#"><?=$this->transEsc('Ask a Librarian')?></a></li>
    <li><a href="#"><?=$this->transEsc('FAQs')?></a></li>
  </ul>
</div>
<div class="span-5 last"><p><strong><?=$this->transEsc('Service')?></strong></p>
    <ul>
        <li><a href="#"><?=$this->transEsc('Contact')?></a></li>
        <li><a href="#"><?=$this->transEsc('Imprint')?></a></li>
        <li><a href="#"><?=$this->transEsc('Questions and Proposals')?></a></li>
        <li><a href="#"><?=$this->transEsc('Weblog')?></a></li>
    </ul>
</div>
<div class="copyright">
    <ul>
        <li>&copy; ZtG 2014</li>
        <li>Zuletzt geändert: 29.06.2014</li>
        <li><a href="#">Seite bearbeiten</a></li>
        <li>Powered by Vufind</li>
    </ul>
</div>
<div class="share">
    <ul>
        <li>
            <a title="Die HU bei Facebook" href="http://www.facebook.com/humboldtuni" class="fb">
                <span class="hiddenStructure">Die HU bei Facebook</span>
            </a>
        </li>
        <li>
            <a title="Die HU bei Twitter" href="http://twitter.com/humboldtUni" class="tw">
                <span class="hiddenStructure">Die HU bei Twitter</span>
            </a>
        </li>
        <li>
            <a title="Die HU bei YouTube" href="http://www.youtube.com/user/humboldtuniberlin?blend=1&amp;ob=5" class="yt">
                <span class="hiddenStructure">Die HU bei YouTube</span>
            </a>
        </li>
        <li>
            <a title="Die HU bei iTunes" href="http://deimos.apple.com/WebObjects/Core.woa/Browsev2/cms.hu-berlin.de-dz" class="it">
                <span class="hiddenStructure">Die HU bei iTunes</span>
            </a>
        </li>
        <li>
            <a title="Die RSS-Feeds der HU" href="http://www.hu-berlin.de/pr/aktuell/rss-info_html" class="rss">
                <span class="hiddenStructure">Die RSS-Feeds der HU</span>
            </a>
        </li>
    </ul>
</div>
<div class="clear"></div>
