<?
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    // Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();

    // Activate Syndetics Plus if necessary:
    if ($this->syndeticsPlus()->isActive()) {
        $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
    }
?>
<table cellpadding="2" cellspacing="0" border="0" class="citation" summary="<?=$this->transEsc('Description')?>">

    <? $documentType = $this->driver->getDocumentType(); ?>
    <? if (isset($documentType) && "" != $documentType): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Document Type')?>: </th>
            <td property="type"><?= $this->escapeHtml($documentType); ?></td>
        </tr>
    <? endif; ?>

    <? $titleShort = $this->driver->getShortTitle(); ?>
    <? if (isset($titleShort)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title Short')?>: </th>
            <td property="shorttitle"><?= $this->escapeHtml($titleShort); ?></td>
        </tr>
    <? endif; ?>

    <? $titleSub = $this->driver->getTitleSub(); ?>
    <? if (isset($titleSub)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title Sub')?>: </th>
            <td property="titlesub"><?= $this->escapeHtml($titleSub); ?></td>
        </tr>
    <? endif; ?>

    <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
    <? if (!empty($authors['main']) || !empty($authors['additional'])):  ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Authors')?>: </th>
            <? // Funny  &gt; to avoid unwanted whitespace ?>
            <td><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></span
            <? foreach ($authors['additional'] as $field): ?>
                >; <span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span
            <? endforeach; ?>
            ></td>
        </tr>
    <? endif; ?>

     <!-- Herausgeber -->
    <? $editors = $this->driver->getEditors(); ?>
    <? if (!empty($editors)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Editors')?>: </th>
            <td property="editor">
            <? foreach ($editors as $editor): ?>
                <a href="<?= $this->record($this->driver)->getLink('author', $editor) ?>"><?= $this->escapeHtml($editor) ?></a><?= $editor !== end($editors) ? "; " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
  
<? $translatedTopics = $this->driver->getTranslatedTopic(); ?>
    <? if (!empty($translatedTopics)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Translation')?>: </th>
            <td property="translation">
            <? foreach ($translatedTopics as $translatedTopic): ?>
                 <?=$this->escapeHtml($translatedTopic)?><br/><?= $translatedTopic !== end($translatedTopics) ? " " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

<? $projects = $this->driver->getProjects(); ?>
    <? if (!empty($projects)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Projects')?>: </th>
            <td property="editor">
            <? foreach ($projects as $project): ?>
              <a href="/Search/Results?lookfor=%22<?=$this->escapeHtml($project)?>%22&type=AllFields"><?=$this->escapeHtml($project)?></a>
              <br/><?= $project !== end($projects) ? " " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
  
    <? $entities = $this->driver->getEntities(); ?>
    <? if (!empty($entities)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
          <th><?=$this->transEsc('Entities')?>: </th>
            <td property="entity">
            <? foreach ($entities as $entity): ?>
            <a href="<?= $this->record($this->driver)->getLink('editor', $entity) ?>"><?= $this->escapeHtml($entity) ?></a><?= $entity !== end($entities) ? "; " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $reviewer = $this->driver->getReviewer(); ?>
    <? if (isset($reviewer)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Reviewer')?>: </th>
            <td property="reviewer"><?= $this->escapeHtml($reviewer); ?></td>
        </tr>
    <? endif; ?>

    <? $shelfMark = $this->driver->getShelfMark(); ?>
    <? if (isset($shelfMark)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('SignaturGenderbib')?>: </th>
            <td property=shelfmark"><?= $this->escapeHtml($shelfMark) ?></td>
        </tr>
    <? endif; ?>

    <? $langs = $this->driver->getLanguages();
    if (!empty($langs)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Language') ?>:</th>
            <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang) ?><?= $lang !== end($langs) ? ", " : "" ?><? endforeach; ?></td>
        </tr>
    <? endif; ?>

    <!-- Mini Kontext -->
    <? $belongsTo = $this->driver->getBelongsTo();
    if (!empty($belongsTo)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Belongs to') ?>:</th>
            <td>
                <a href="<?= $this->url('record') . $belongsTo[0] ?>"><?= $belongsTo[1] ?></a>
            </td>
        </tr>
    <? endif; ?>

    <? $belongsToTop = $this->driver->getBelongsToTop();
    if (!empty($belongsToTop)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Belongs to Top') ?>:</th>
            <td>
                <a href="<?= $this->url('record') . $belongsToTop[0] ?>"><?= $belongsToTop[1] ?></a>
            </td>
        </tr>
    <? endif; ?>


    <!-- Schriftenreihe -->
    <? /* Display series section if at least one series exists. */ ?>
    <? $series = $this->driver->getSeries();
    if (!empty($series)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Series') ?>:</th>
            <td>
                <? foreach ($series as $field): ?>
                    <? /* Depending on the record driver, $field may either be an array with
             "name" and "number" keys or a flat string containing only the series
             name.  We should account for both cases to maximize compatibility. */
                    ?>
                    <? if (is_array($field)): ?>
                        <? if (!empty($field['name'])): ?>
                            <a href="<?= $this->record($this->driver)->getLink('series', $field['name']) ?>"><?= $this->escapeHtml($field['name']) ?></a>
                            <? if (!empty($field['number'])): ?>
                                <?= $this->escapeHtml($field['number']) ?>
                            <? endif; ?>
                            <br/>
                        <? endif; ?>
                    <? else: ?>
                        <a href="<?= $this->record($this->driver)->getLink('series', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                        <br/>
                    <? endif; ?>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>




    <? $issues = $this->driver->getIssues(); ?>
    <? if (!empty($issues)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Issue')?>: </th>
            <td property=issue">
            <? foreach($issues as $issue): ?>
                <?= $this->escapeHtml($issue) ?><?= $issue !== end($issues) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $volumes = $this->driver->getVolumes(); ?>
    <? if (!empty($volumes)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Volume')?>: </th>
            <td property=volume">
            <? foreach($volumes as $volume): ?>
                <?= $this->escapeHtml($volume) ?><?= $volume !== end($volumes) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $timeSpanStart = $this->driver->getTimeSpanStart(); ?>
    <? $timeSpanEnd = $this->driver->getTimeSpanEnd(); ?>
    <? if (isset($timeSpanStart) || isset($timeSpanEnd)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Time span')?>: </th>
            <td property="time">
            <? if (isset($timeSpanStart)): ?>
                <?= $this->escapeHtml($timeSpanStart) ?>
                <? if (isset($timeSpanEnd)): ?>
                    -
                    <?= $this->escapeHtml($timeSpanEnd) ?>
                <? endif ?>
             <? elseif (isset($timeSpanEnd)): ?>
                <?= $this->escapeHtml($timeSpanEnd) ?>
            <? endif; ?>
            </td>
        </tr>
    <? endif; ?>



    <? $dimensions = $this->driver->getDimensions(); ?>
    <? if (!empty($dimensions)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Dimension')?>: </th>
            <td property="dimension">
            <? foreach ($dimensions as $dimension): ?>
                <?=$this->escapeHtml($dimension)?><?= $dimension !== end($dimensions) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    

    
    <? $runTimes = $this->driver->getRunTimes(); ?>
    <? if (!empty($runTimes)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Run Time')?>: </th>
            <td property="runTime">
            <? foreach ($runTimes as $runTime): ?>
                <?=$this->escapeHtml($runTime)?><?= $runTime !== end($runTimes) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

   


    <? $isbns = $this->driver->getISBNs(); ?>
    <? if (!empty($isbns)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ISBN')?>: </th>
            <td property="isbn">
            <? foreach ($isbns as $field): ?>
                <?=$this->escapeHtml($field)?><?= $field !== end($isbns) ? ", " : "" ?>
                 </td>
        </tr>
         <tr valign="top">
            <th><a name=bookstores></a><?=$this->transEsc('Bookstores')?>: </th>
            <td property="bookstore">
                <? $isbn = $this->driver->getCleanISBN() ?>
                <? $amazonassociate = $this->driver->getAmazonAffiliateId() ?>
                <? if ($isbn && $amazonassociate): ?>
                <div style="margin: .7em 0 1em .5em; line-height:1.5em;">
                   <a href="http://www.amazon.de/gp/product/<?= $isbn ?>?tag=<?= $amazonassociate ?>" target="_blank" title="<?= $this->transEsc('Buy from Amazon') ?>">amazon</a> <i class="fa fa-external-link"></i><br />
                    <a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $isbn ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7</a> <i class="fa fa-external-link"></i><br />
                    <a href="http://www.booklooker.de/B%C3%BCcher/Angebote/isbn=<?= $isbn ?>?lid=1" target=_blank>booklooker</a> <i class="fa fa-external-link"></i><br />
	      <a href="http://www.zvab.com/basicSearch.do?anyWords=<?= $isbn ?>&author=&title=&check_sn=on" target=_blank>ZVAB</a> <i class="fa fa-external-link"></i></div>
                    <? endif; ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    
     <? $isbns = $this->driver->getISBNs(); ?>
     <? $formats = $this->driver->getFormats(); ?>
     <? $issns = $this->driver->getISSNs(); ?>
     <? $zdbids = $this->driver->getZDBIDs(); ?>
     <? if (empty($isbns) && empty($issns) && empty($zdbids) && (($formats[0]=="Buch") || ($formats[0]=="Artikel"))): ?>
     <? $displayTitle = $this->driver->getdisplayTitle(); ?>
     <? $titleShort = $this->driver->getShortTitle(); ?>
     <? $titleShortPregReplace = preg_replace ( '/[^a-z0-9 äüö]/i', '', $titleShort ) ?>
     <? $titleSub = $this->driver->getTitleSub(); ?>
     <? $editors = $this->driver->getEditors(); ?>
     <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
     <? $belongsToTop = $this->driver->getBelongsToTop(); ?>
     <? $belongsToTopPregReplace = preg_replace ( '/[^a-z0-9 äüö]/i', '', $belongsToTop[1] ) ?>
     <?php function umlautepas($string){
     	$upas = Array("ä" => "ae", "ü" => "ue", "ö" => "oe", "Ä" => "Ae", "Ü" => "Ue", "Ö" => "Oe"); 
     	return strtr($string, $upas);
     } ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><a name=bookstores></a><?=$this->transEsc('Bookstores')?>: </th>
            <td property="shop">
            <? $amazonassociate = $this->driver->getAmazonAffiliateId() ?>
       
       <? if (!empty($belongsToTop)):
       		$search_term = $belongsToTopPregReplace;
       		$search_term = $search_term . ' ' . $this->escapeHtml($editors[0]);
       		else:
       			$search_term = $titleShortPregReplace . ' ' . $this->escapeHtml($authors['main'] . ' ' . $this->escapeHtml($editors[0]));
       			endif;
       		?>
  	<div style="margin: .7em 0 1em .5em; line-height:1.5em;">
  	<a href="http://www.amazon.de/s/field-keywords=<?= $search_term ?>?tag=<?= $amazonassociate ?>&node=186606" target=_blank>amazon</a> <i class="fa fa-external-link"></i><br />
  	<? if  ($formats[0]=="Artikel"): ?>
  		<a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $search_term ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7</a> <i class="fa fa-external-link"></i><br />
  		<? else: ?>
  			<a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $titleShortPregReplace ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7</a> <i class="fa fa-external-link"></i><br />
  			<? endif; ?>
  	<? if  ($formats[0]=="Artikel"): ?>
  		<a href="http://www.booklooker.de/B%C3%BCcher/Angebote/titel=<?= umlautepas($search_term) ?>" target=_blank>booklooker</a> <i class="fa fa-external-link"></i><br />
  		<? else: ?>
  			<a href="http://www.booklooker.de/B%C3%BCcher/Angebote/titel=<?= umlautepas($search_term) ?>" target=_blank>booklooker</a> <i class="fa fa-external-link"></i><br />
  			<? endif; ?>
  	<a href="http://www.zvab.com/servlet/SearchResults?kn=<?= umlautepas($search_term) ?>" target=_blank>ZVAB</a> <i class="fa fa-external-link"></i>
        	</div>
        	</td>
        </tr>
    <? endif; ?>
       


    
    <? $issns = $this->driver->getISSNs(); ?>
    <? if (!empty($issns)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ISSN')?>: </th>
            <td property="issn">
            <? foreach ($issns as $field): ?>
                <?=$this->escapeHtml($field)?><?= $field !== end($issns) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    
    <? $zdbids = $this->driver->getZDBIDs(); ?>
    <? if (!empty($zdbids)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ZDBID')?>: </th>
            <td property="zdbid">
            <? foreach ($zdbids as $field): ?>
                <a target=_blank href="http://beta.zdb-opac.de/zdb/list.xhtml?t=
               <?=$this->escapeHtml($field)?>"><?=$this->escapeHtml($field)?></a> <i class="fa fa-external-link"></i>
               <?= $field !== end($zdbids) ? "<p/> " : "" ?>
               <!-- <?=$this->escapeHtml($field)?><?= $field !== end($zdbids) ? ", " : "" ?>-->
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $description = $this->driver->getDescription(); ?>
    <? if (isset($description)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Description')?>: </th>
            <td property=description"><?= $this->escapeHtml($description) ?></td>
        </tr>
    <? endif; ?>

    <? $signatory = $this->driver->getSignatory(); ?>
    <? if (isset($signatory)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Signatory')?>: </th>
            <td property=signatory"><?= $this->escapeHtml($signatory) ?></td>
        </tr>
    <? endif; ?>

    <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
    <? if ($QRCode): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('QRCode')?>: </th>
            <td style="padding: 0px;"><img alt="<?= $this->transEsc('QR Code') ?>" class="qrcode" src="<?= $this->escapeHtml($QRCode); ?>"/></td>
        </tr>
    <? endif; ?>

    <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
        <tr><td><?=$this->transEsc('no_description')?></td></tr>
    <? endif; ?>
</table>
