<?
    // Set page title.
    $this->headTitle($this->translate('further information') . ': ' . $this->driver->getBreadcrumb());

    // Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();

    // Activate Syndetics Plus if necessary:
    if ($this->syndeticsPlus()->isActive()) {
        $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
    }
?>
<table id="detail-view-description" cellpadding="0" cellspacing="0" border="0" summary="<?=$this->transEsc('further information')?>">

<?php /* Not required
    <? $formats = $this->driver->getFormats(); ?>
    <? if (!empty($formats)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Format')?>: </th>
            <td property="format"><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
    <? endif; ?>
*/?>
    
    <? $institutions = $this->driver->getInstitutions(); ?>
    <? if (!empty($institutions)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Institution')?>: </th>
            <td property="institution">
            <? foreach($institutions as $institution): ?>
             <a href="#link"><?= $this->transEsc($institution) ?><?= $institution !== end($institutions) ? ", " : "" ?></a>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    
    <? $location = $this->driver->getLocation(); ?>
    <? if (isset($location)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Location')?>: </th>
            <td property="location"><?= $this->escapeHtml($location); ?></td>
        </tr>
    <? endif; ?>
    
    <? $documentType = $this->driver->getDocumentType(); ?>
    <? if (isset($documentType) && "" != $documentType): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Document Type')?>: </th>
            <td property="type"><?= $this->escapeHtml($documentType); ?></td>
        </tr>
    <? endif; ?>
    <? $signatory = $this->driver->getSignatory(); ?>
    <? if (isset($signatory)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Signatory')?>: </th>
            <td property="signatory"><?= $this->escapeHtml($signatory) ?></td>
        </tr>
    <? endif; ?>
<!--
    <? $displayTitle = $this->driver->getdisplayTitle(); ?>
    <? if (isset($displayTitle)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title')?>: </th>
            <td property="title"><?= $this->escapeHtml($displayTitle); ?></td>
        </tr>
    <? endif; ?>

    <? $titleShort = $this->driver->getShortTitle(); ?>
    <? if (isset($titleShort)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title Short')?>: </th>
            <td property="shorttitle"><?= $this->escapeHtml($titleShort); ?></td>
        </tr>
    <? endif; ?>

    <? $titleSub = $this->driver->getTitleSub(); ?>
    <? if (isset($titleSub)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title Sub')?>: </th>
            <td property="titlesub"><?= $this->escapeHtml($titleSub); ?></td>
        </tr>
    <? endif; ?>-->

    <? $alternativeTitles = $this->driver->getAlternativeTitles(); ?>
    <? if (!empty($alternativeTitles)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Title variation')?>: </th>
            <td property="issue">
            <? foreach($alternativeTitles as $alternativeTitle): ?>
                <?= $this->escapeHtml($alternativeTitle) ?><?= $alternativeTitle !== end($alternativeTitles) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
    <? if (!empty($authors['main']) || !empty($authors['additional'])):  ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Authors')?>: </th>
            <? // Funny  &gt; to avoid unwanted whitespace ?>
            <td><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></span
            <? foreach ($authors['additional'] as $field): ?>
                >; <span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span
            <? endforeach; ?>
            ></td>
        </tr>
    <? endif; ?>

     <!-- Herausgeber -->
    <? $editors = $this->driver->getEditors();   
        if (!empty($editors)): ?>
    
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Editors')?>: </th>
            <td property="editor">
            <? foreach ($editors as $editor): ?>
                <a href="<?= $this->record($this->driver)->getLink('editor', $editor) ?>"><?= $this->escapeHtml($editor) ?></a><?= $editor !== end($editors) ? "; " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    

    <? $contributors = $this->driver->getContributors();
    if (!empty($contributors)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Contributor') ?>:</th>
            <td><? foreach ($contributors as $contributor): ?><?= $this->escapeHtml($contributor) ?><?= $contributor !== end($contributors) ? " <br /> " : "" ?><? endforeach; ?></td>
        </tr>
    <? endif; ?>

    
      <? $sourceInfo = $this->driver->getSourceInfos(); ?>
            <? if (!empty($sourceInfo)): ?>
                <? $top = $this->driver->getBelongsToTop(); ?>
                <tr valign="top">
            <th><?= $this->transEsc('Source') ?>:</th>
            <td>
                <? foreach($sourceInfo as $info): ?>
                    <? $inText = $this->escapeHtml($info) ?>
                    <? if (substr($top[1], 0, strlen($info)) === $info): ?>
                        <a href="<?= $this->recordLink()->getUrl($top[0]) ?>">
                            <?= $inText ?>
                        </a>
                    <? else: ?>
                        <?= $inText ?>
                    <? endif; ?>
                    <?= $info !== end($sourceInfo) ? ", " : "" ?>
                <? endforeach; ?>
               </td>
        </tr>
            <? endif; ?>
    
    <? $contributorsNoFacet = $this->driver->getContributorsNoFacet();
    if (!empty($contributorsNoFacet)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Contributor') ?>:</th>
            <td>
	      <? foreach ($contributorsNoFacet as $contributorNoFacet): ?>
		<?= $this->escapeHtml($contributorNoFacet) ?>
		<?= $contributorNoFacet !== end($contributorsNoFacet) ? ", " : "" ?>
		<? endforeach; ?>
	      </td>
        </tr>
    <? endif; ?>
  
    <? $entities = $this->driver->getEntities(); ?>
    <? if (!empty($entities)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
          <th><?=$this->transEsc('Entities')?>: </th>
            <td property="entity">
            <? foreach ($entities as $entity): ?>
	    <?= $this->escapeHtml($entity) ?>
	    <?= $entity !== end($entities) ? "; " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
  


<? $projects = $this->driver->getProjects(); ?>
    <? if (!empty($projects)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Projects')?>: <a href="#"  title="Im Rahmen eines Pilotprojekts wurden in Zusammenarbeit mit EIGE, dem European Institute for Gender Equality, 10 Themebereiche benannt. Die Zurordnung der Datensätze, zu den einzelnen Themenbereichen, erfolgt automatisch über Schlagworte."><i class="fa fa-info-circle"></i></a> </th>
            <td property="editor">
            <? foreach ($projects as $project): ?>
              <a href="/Search/Results?lookfor=%22<?=$this->escapeHtml($project)?>%22&type=AllFields"><?=$this->escapeHtml($project)?></a>
              <br/><?= $project !== end($projects) ? " " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
  
    <!--ENTFERNT VON MARIUS<? $entities = $this->driver->getEntities(); ?>
    <? if (!empty($entities)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
          <th><?=$this->transEsc('Entities')?>: </th>
            <td property="entity">
            <? foreach ($entities as $entity): ?>
            <a href="<?= $this->record($this->driver)->getLink('editor', $entity) ?>"><?= $this->escapeHtml($entity) ?></a><?= $entity !== end($entities) ? "; " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>-->
    
    <? $reviewers = $this->driver->getReviewer(); ?>
    <? if (isset($reviewers)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Reviewer')?>: </th>
            <td property="shelfmark"><?= $this->escapeHtml($reviewers) ?></td>
        </tr>
    <? endif; ?>
    
    
    <!--<? $reviewers = $this->driver->getReviewer(); ?>
    <? if (isset($reviewers)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Reviewer')?>: </th>
            <td property="reviewer">
	      <? foreach ($reviewers as $reviewer): ?>
		<?= $this->escapeHtml($reviewer) ?>
		<?= $reviewer !== end($reviewers) ? ";  " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>-->
    
    
<?php if ($this->driver->isArchive()): ?>
	  <? $shelfMark = $this->driver->getShelfMark(); ?>
	  <? if (isset($shelfMark)): ?>
	  <? $contentDisplayed = true; ?>
	  <tr valign="top">
            <th><?=$this->transEsc('Shelf Mark')?>: </th>
            <td property="shelfmark"><?= $this->escapeHtml($shelfMark) ?></td>
        </tr>
      <? endif; ?>
	  <?php endif; ?>



	  
   <!-- <? $shelfMark = $this->driver->getShelfMark(); ?>
    <? if (isset($shelfMark)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Shelf Mark')?>: </th>
            <td property="shelfmark"><?= $this->escapeHtml($shelfMark) ?></td>
        </tr>
    <? endif; ?>-->

    <!--<? $langs = $this->driver->getLanguages();
    if (!empty($langs)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Language') ?>:</th>
            <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang) ?><?= $lang !== end($langs) ? ", " : "" ?><? endforeach; ?></td>
        </tr>
    <? endif; ?>-->





    <!-- Schriftenreihe -->
    <? $series = $this->driver->getSeries();
    if (!empty($series)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Series') ?>:</th>
            <td>
                <? foreach ($series as $field): ?>
                    <? // Depending on the record driver, $field may either be an array with "name" and "number" keys or a flat string containing only the series name.  We should account for both cases to maximize compatibility.
                    ?>
                    <? if (is_array($field)): ?>
                        <? if (!empty($field['name'])): ?>
                            <a href="<?= $this->record($this->driver)->getLink('series', $field['name']) ?>"><?= $this->escapeHtml($field['name']) ?></a>
                            <? if (!empty($field['number'])): ?>
                                <?= $this->escapeHtml($field['number']) ?>
                            <? endif; ?>
                            <br/>
                        <? endif; ?>
                    <? else: ?>
                        <a href="<?= $this->record($this->driver)->getLink('series', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                        <br/>
                    <? endif; ?>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?> 

<?php /* Not required
    <? $placesOfPublication = $this->driver->getPlacesOfPublication(); ?>
    <? if (!empty($placesOfPublication)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Place of publication')?>: </th>
            <td property=location">
            <? foreach($placesOfPublication as $placeOfPublication): ?>
                <?= $this->escapeHtml($placeOfPublication) ?><?= $placeOfPublication !== end($placesOfPublication) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    */?>
    
<?php /* Not required
    <? $publishers = $this->driver->getPublishers(); ?>
    <? if (!empty($publishers)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Publisher')?>: </th>
            <td property=publisher">
            <? foreach($publishers as $publisher): ?>
                <?= $this->escapeHtml($publisher) ?><?= $publisher !== end($publishers) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>*/?>

<? $publicationDate = $this->driver->getDisplayPublicationDate(); ?>
<? $editions = $this->driver->getEditions();  ?>
     <? if (empty($publicationDate) && !empty($editions)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?= $this->transEsc('Edition') ?>:</th>
            <td><? foreach ($editions as $edition): ?><?= $this->escapeHtml($edition) ?><?= $edition !== end($editions) ? " <br /> " : "" ?><? endforeach; ?></td>
        </tr>
    <? endif; ?>

    <? $publicationDate = $this->driver->getDisplayPublicationDate(); ?>
    <? if (isset($publicationDate)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Date of publication')?>: </th>
            <td property=publicationDate"><?= $this->escapeHtml($publicationDate) ?></td>
        </tr>
    <? endif; ?>

    <? $issues = $this->driver->getIssues(); ?>
    <? if (!empty($issues)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Issue')?>: </th>
            <td property="issue">
            <? foreach($issues as $issue): ?>
                <?= $this->escapeHtml($issue) ?><?= $issue !== end($issues) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $volumes = $this->driver->getVolumes(); ?>
    <? if (!empty($volumes)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Volume')?>: </th>
            <td property="volume">
            <? foreach($volumes as $volume): ?>
                <?= $this->escapeHtml($volume) ?><?= $volume !== end($volumes) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $provenances = $this->driver->getProvenances(); ?>
    <? if (!empty($provenances)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Provenance')?>: </th>
            <td property="provenance">
            <? foreach($provenances as $provenance): ?>
                <?= $this->escapeHtml($provenance) ?><?= $provenance !== end($provenances) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $specificMaterialDesignations = $this->driver->getSpecificMaterialDesignations(); ?>
    <? if (!empty($specificMaterialDesignations)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Description')?>: </th>
            <td property="specificMaterialDesignations">
            <? foreach($specificMaterialDesignations as $specificMaterialDesignation): ?>
                 <?= $specificMaterialDesignation ?><?= $specificMaterialDesignation !== end($specificMaterialDesignations) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

   <!-- <? $timeSpanStart = $this->driver->getTimeSpanStart(); ?>
    <? $timeSpanEnd = $this->driver->getTimeSpanEnd(); ?>
    <? if (isset($timeSpanStart) || isset($timeSpanEnd)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Time span')?>: </th>
            <td property="time">
            <? if (isset($timeSpanStart)): ?>
                <?= $this->escapeHtml($timeSpanStart) ?>
                <? if (isset($timeSpanEnd)): ?>
                    -
                    <?= $this->escapeHtml($timeSpanEnd) ?>
                <? endif ?>
             <? elseif (isset($timeSpanEnd)): ?>
                <?= $this->escapeHtml($timeSpanEnd) ?>
            <? endif; ?>
            </td>
        </tr>
    <? endif; ?>-->
<?php /* Not required
    <? $physicals = $this->driver->getPhysicalDescriptions(); ?>
    <? if (!empty($physicals)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Pages')?>: </th>
            <td property="page">
            <? foreach ($physicals as $physical): ?>
                <?=$this->escapeHtml($physical)?><?= $physical !== end($physicals) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>*/?>

    <? $dimensions = $this->driver->getDimensions(); ?>
    <? if (!empty($dimensions)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Dimension')?>: </th>
            <td property="dimension">
            <? foreach ($dimensions as $dimension): ?>
                <?=$this->escapeHtml($dimension)?><?= $dimension !== end($dimensions) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $runTimes = $this->driver->getRunTimes(); ?>
    <? if (!empty($runTimes)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Run Time')?>: </th>
            <td property="runTime">
            <? foreach ($runTimes as $runTime): ?>
                 <?= $runTime ?><?= $runTime !== end($runTimes) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

<?php /* Not required
    <!-- Schlagworte -->
    <? $subjects = $this->driver->getAllSubjectHeadings(); ?>
    <? if (!empty($subjects)): ?>
        <? $contentDisplayed = true; ?>
        <? foreach(array("Topic", "Geo", "Person") as $type): ?>
            <tr valign="top">
                <? if (isset($subjects[strtolower($type)])): ?>
                    <th><?= $this->transEsc('Subjects ' . $type) ?>:</th>
                    <td property="keywords <?= strtolower($type) ?>">
                        <? $fields = $subjects[strtolower($type)]; ?>
                        <? foreach ($fields as $subject): ?>
                            <a title="<?= $this->escapeHtml($subject) ?>"
                               href="<?= $this->record($this->driver)->getLink('subject', $subject) ?>">
                               <?= $this->escapeHtml($subject) ?></a><?= $subject !== end($fields) ? ", " : "" ?>
                               <? // Keep above in one line to avoid unwanted whitespace ?>
                        <? endforeach; ?>
                    </td>
                <? endif; ?>
            </tr>
        <? endforeach; ?>
    <? endif; ?>*/?>




    <? $issns = $this->driver->getISSNs(); ?>
    <? if (!empty($issns)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ISSN')?>: </th>
            <td property="issn">
            <? foreach ($issns as $field): ?>
                 <a target=_blank href="http://beta.zdb-opac.de/zdb/list.xhtml?t=
                <?=$this->escapeHtml($field)?>"><?=$this->escapeHtml($field)?> <i class="fa fa-external-link"></i></a>
                <?= $field !== end($issns) ? "<p/> " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? $zdbids = $this->driver->getZDBIDs(); ?>
    <? if (!empty($zdbids)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ZDBID')?>: </th>
            <td property="zdbid">
            <? foreach ($zdbids as $field): ?>
               <a target=_blank href="http://beta.zdb-opac.de/zdb/list.xhtml?t=
               <?=$this->escapeHtml($field)?>"><?=$this->escapeHtml($field)?> <i class="fa fa-external-link"></i></a> 
               <?= $field !== end($zdbids) ? "<p/> " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>


    
     <? $listOfContents = $this->driver->getListOfContents();
    if (!empty($listOfContents)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th colspan="2"><?= $this->transEsc('Inhaltsangabe') ?>:</th>
          </tr>
          <tr valign="top">
            <td property="description" colspan="2">
            <? foreach ($listOfContents as $listOfContent): ?>
            <li style="list-style-type: none; diplay:block; margin-bottom:.5em">
           <!-- <?= $this->escapeHtmlAllowBr($listOfContent) ?><?= $listOfContent !== end($listOfContents) ? " " : "" ?>-->
            <?= $listOfContent ?><?= $listOfContent !== end($listOfContents) ? " " : "" ?>
           </li>
           <? endforeach; ?>
               
            </td>
        </tr>
    <? endif; ?>
   
    <? $collectionHolding = $this->driver->getCollectionHolding(); ?>
    <? if (isset($collectionHolding)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Bestand')?>:</th>
            <td property="collectionHolding" colspan="2">
              <!-- <?= $this->escapeHtml($collectionHolding) ?>-->
                 <?= $collectionHolding ?>
           </td>
        </tr>
    <? endif; ?>
    
   <!--neu eingefügt-->
   
   <? $outofstocks = $this->driver->getOutOfStocks(); ?>
    <? if (!empty($outofstocks)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Out of stock')?>: </th>
            <td property=volume">
            <? foreach($outofstocks as $outofstock): ?>
                <?= $this->escapeHtml($outofstock) ?><?= $outofstock !== end($outofstocks) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

<? $publicationfrequencys = $this->driver->getPublicationFrequency(); ?>
    <? if (!empty($publicationfrequencys)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Publication frequency')?>: </th>
            <td property=volume">
            <? foreach($publicationfrequencys as $publicationfrequency): ?>
                <?= $this->escapeHtml($publicationfrequency) ?><?= $publicationfrequency !== end($publicationfrequencys) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
<? $specialissues = $this->driver->getSpecialIssue(); ?>
    <? if (!empty($specialissues)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Special Issues')?>: </th>
            <td property=volume">
            <? foreach($specialissues as $specialissue): ?>
                <?= $this->escapeHtml($specialissue) ?><?= $specialissue !== end($specialissues) ? ", " : "" ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
   
   
    <? $isbns = $this->driver->getISBNs(); ?>
    <? if (!empty($isbns)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('ISBN')?>: </th>
            <td property="isbn">
            <? foreach ($isbns as $field): ?>
                <?=$this->escapeHtml($field)?><?= $field !== end($isbns) ? ", " : "" ?>
                 </td>
        </tr>
         <tr valign="top">
            <th><a name=bookstores></a><?=$this->transEsc('Bookstores')?>: </th>
            <td property="bookstore">
                <? $isbn = $this->driver->getCleanISBN() ?>
                <? $amazonassociate = $this->driver->getAmazonAffiliateId() ?>
                <? if ($isbn): ?>
              
                <div style="margin: .7em 0 1em .5em; line-height:1.5em;">
                   <a href="http://www.amazon.de/gp/product/<?= $isbn ?>?tag=<?= $amazonassociate ?>" target="_blank" title="<?= $this->transEsc('Buy from Amazon') ?>">amazon <i class="fa fa-external-link"></i></a><br />
                    <a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $isbn ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7 <i class="fa fa-external-link"></i></a><br />
                    <a href="http://www.booklooker.de/B%C3%BCcher/Angebote/isbn=<?= $isbn ?>?lid=1" target=_blank>booklooker <i class="fa fa-external-link"></i></a><br />
	      <a href="http://www.zvab.com/basicSearch.do?anyWords=<?= $isbn ?>&author=&title=&check_sn=on" target=_blank>ZVAB <i class="fa fa-external-link"></i></a></div>
                    <? endif; ?>
            <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
    
     <? $isbns = $this->driver->getISBNs(); ?>
     <? $formats = $this->driver->getFormats(); ?>
     <? $issns = $this->driver->getISSNs(); ?>
     <? $zdbids = $this->driver->getZDBIDs(); ?>
     <? if (empty($isbns) && empty($issns) && empty($zdbids) && (($formats[0]=="Buch") || ($formats[0]=="Artikel"))): ?>
     <? $displayTitle = $this->driver->getdisplayTitle(); ?>
     <? $titleShort = $this->driver->getShortTitle(); ?>
     <? $titleShortPregReplace = preg_replace ( '/[^a-z0-9 äüö]/i', '', $titleShort ) ?>
     <? $titleSub = $this->driver->getTitleSub(); ?>
     <? $editors = $this->driver->getEditors(); ?>
     <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
     <? $belongsToTop = $this->driver->getBelongsToTop(); ?>
     <? $belongsToTopPregReplace = preg_replace ( '/[^a-z0-9 äüö]/i', '', $belongsToTop[1] ) ?>
     <?php function umlautepas($string){
     	$upas = Array("ä" => "ae", "ü" => "ue", "ö" => "oe", "Ä" => "Ae", "Ü" => "Ue", "Ö" => "Oe"); 
     	return strtr($string, $upas);
     } ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><a name=bookstores></a><?=$this->transEsc('Bookstores')?>: </th>
            <td property="shop">
            <? $amazonassociate = $this->driver->getAmazonAffiliateId() ?>
       
       <? if (!empty($belongsToTop)):
       		$search_term = $belongsToTopPregReplace;
       		$search_term = $search_term . ' ' . $this->escapeHtml($editors[0]);
       		else:
       			$search_term = $titleShortPregReplace . ' ' . $this->escapeHtml($authors['main'] . ' ' . $this->escapeHtml($editors[0]));
       			endif;
       		?>
  	<div style="margin: .7em 0 1em .5em; line-height:1.5em;">
  	<a href="http://www.amazon.de/s/field-keywords=<?= $search_term ?>?tag=<?= $amazonassociate ?>&node=186606" target=_blank>amazon <i class="fa fa-external-link"></i></a><br />
  	<? if  ($formats[0]=="Artikel"): ?>
  		<a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $search_term ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7 <i class="fa fa-external-link"></i></a><br />
  		<? else: ?>
  			<a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $titleShortPregReplace ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7 <i class="fa fa-external-link"></i></a><br />
  			<? endif; ?>
  	<? if  ($formats[0]=="Artikel"): ?>
  		<a href="http://www.booklooker.de/B%C3%BCcher/Angebote/titel=<?= umlautepas($search_term) ?>" target=_blank>booklooker <i class="fa fa-external-link"></i></a><br />
  		<? else: ?>
  			<a href="http://www.booklooker.de/B%C3%BCcher/Angebote/titel=<?= umlautepas($search_term) ?>" target=_blank>booklooker <i class="fa fa-external-link"></i></a><br />
  			<? endif; ?>
  	<a href="http://www.zvab.com/servlet/SearchResults?kn=<?= umlautepas($search_term) ?>" target=_blank>ZVAB <i class="fa fa-external-link"></i></a>
        	</div>
        	</td>
        </tr>
    <? endif; ?>
   
   <!--ENDE-->
   
   <? $descriptions = $this->driver->getDescriptions(); ?>
    <? if (!empty($descriptions)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
             <th colspan="2"><?=$this->transEsc('Description')?>:</th>
	     </tr>
	     <tr valign="top">
	     <td property="description" colspan="2">
		<? foreach ($descriptions as $description): ?>
		<?= $description ?>
		<?= $description !== end($descriptions) ? "<br/> " : "" ?>
	      <? endforeach; ?>
	     </td>        
	  </tr>
	<? endif; ?>
   
   <? $annotations = $this->driver->getAnnotations(); ?>
    <? if (!empty($annotations)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
             <th colspan="2"><?=$this->transEsc('Annotation')?>:</th>
             </tr>
	     <tr valign="top">
	      <td property="annotation" colspan="2">
		<? foreach ($annotations as $annotation): ?>
		<?= $annotation ?>
		<?= $annotation !== end($annotations) ? "<br/> " : "" ?>
	      <? endforeach; ?>
	     </td>        
	  </tr>
	<? endif; ?>
   
    <!--<? $creationdate = $this->driver->getRecordCreationDate(); ?>
    <? if (isset($creationdate)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Date')?>: </th>
            <td property="creationdate"><?= $this->escapeHtml($creationdate) ?></td>
        </tr>
    <? endif; ?>-->
    
   <!-- <? $titleShort = $this->driver->getShortTitle(); ?>
    <? if (isset($titleShort)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('Online')?>: </th>
            <td property="shorttitle">
             
             <a href="https://www.buch7.de/store/simple_search_results?utf8=✓&navkat=&search=<?= $this->escapeHtml($titleShort); ?>&commit.x=0&commit.y=0&commit=Suchen" target=_blank>buch7</a>, 
             <a href="http://www.booklooker.de/B%C3%BCcher/Angebote/infotext=<?= $this->escapeHtml($titleShort); ?>?lid=1" target=_blank>booklooker</a>, 
	      <a href="http://www.zvab.com/basicSearch.do?anyWords=<?= $this->escapeHtml($titleShort); ?>&author=&title=&check_sn=on" target=_blank>ZVAB</a>
          </td>
        </tr>
    <? endif; ?> -->
    
    
    <?php if ($this->driver->isLibrary()): ?>
	   <? $shelfMark = $this->driver->getShelfMark(); ?>
	  <? if (isset($shelfMark)): ?>
	  <? $contentDisplayed = true; ?>
	  <tr valign="top">
            <th><?=$this->transEsc('Signatory')?>: </th>
            <td property="shelfmark"><?= $this->escapeHtml($shelfMark) ?></td>
        </tr>
      <? endif; ?>
	  <?php endif; ?>


   <? $sourceInfos = $this->driver->getSourceInfos(); ?>
    <? if (!empty($sourceInfos)): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
             <th colspan="2"><?=$this->transEsc('SourceInfo')?>:</th>
             </tr>
	     <tr valign="top">
	      <td property="annotation" colspan="2">
		<? foreach ($sourceInfos as $sourceInfo): ?>
		<a href="http://meta-katalog.eu/Search/Results?lookfor=%22<?= $this->escapeHtml($sourceInfo); ?>%22&type=Sourceinfo&filter=searchfilter%3A%22ZP+-+Zeitschriftenheft%22"><?= $this->escapeHtml($sourceInfo); ?></a>
		<?= $sourceInfo !== end($sourceInfos) ? "<br/> " : "" ?>
	      <? endforeach; ?>
	     </td>        
	  </tr>
	<? endif; ?>


	 
    <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
    <? if ($QRCode): ?>
        <? $contentDisplayed = true; ?>
        <tr valign="top">
            <th><?=$this->transEsc('QRCode')?>: </th>
            <td style="padding: 0px;"><img alt="<?= $this->transEsc('QR Code') ?>" class="qrcode" src="<?= $this->escapeHtml($QRCode); ?>"/></td>
        </tr>
    <? endif; ?>
    
    

    <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
        <tr><td><?=$this->transEsc('no_description')?></td></tr>
    <? endif; ?>
</table>
