<div class="span-13" vocab="http://schema.org/" resource="#record"
     typeof="<?= $this->driver->getSchemaOrgFormats() ?> Product">
<h1 property="name"><?= $this->escapeHtml($this->driver->getDisplayTitle()); ?></h1>

<? /* Display Main Details */ ?>
<table cellpadding="2" cellspacing="0" border="0" class="citation"
       summary="<?= $this->transEsc('Bibliographic Details') ?>">

    <!-- Format -->
    <? $formats = $this->driver->getFormats();
    if (!empty($formats)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Format') ?>:</th>
            <td><?= $this->record($this->driver)->getFormatList() ?></td>
        </tr>
    <? endif; ?>

    <? $langs = $this->driver->getLanguages();
    if (!empty($langs)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Language') ?>:</th>
            <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang) ?><br/><? endforeach; ?></td>
        </tr>
    <? endif; ?>

    <!-- Autor -->
    <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
    <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Main Author') ?>:</th>
            <td property="author"><a
                    href="<?= $this->record($this->driver)->getLink('author', $authors['main']) ?>"><?= $this->escapeHtml($authors['main']) ?></a>
            </td>
        </tr>
    <? endif; ?>

    <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Corporate Author') ?>:</th>
            <td property="creator"><a
                    href="<?= $this->record($this->driver)->getLink('author', $authors['corporate']) ?>"><?= $this->escapeHtml($authors['corporate']) ?></a>
            </td>
        </tr>
    <? endif; ?>

    <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Other Authors') ?>:</th>
            <td>
                <? $i = 0;
                foreach ($authors['secondary'] as $field): ?><?=
                    ($i++ == 0) ? '' : ', ' ?><span
                        property="contributor"><a
                        href="<?= $this->record($this->driver)->getLink('author', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                    </span><? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <!-- Herausgeber -->
    <? $editors = $this->driver->getEditors();
    if (!empty($editors)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Editors') ?>:</th>
            <td>
                <? foreach ($editors as $editor): ?>
                    <a
                    href="<?= $this->record($this->driver)->getLink('editor', $editor) ?>"><?= $this->escapeHtml($editor) ?></a><? if (next($editors) == true) : ?>; <? endif; ?>
                <? endforeach; ?>
            </td>
        </tr>
    <? else: ?>
        <!-- No Editors -->
    <? endif; ?>

    <!-- Veroeffentlicht -->
    <? $publications = $this->driver->getPublicationDetails();
    if (!empty($publications)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Published') ?>:</th>
            <td>
                <? foreach ($publications as $field): ?>
                    <span property="publisher" typeof="Organization">
          <? $pubPlace = $field->getPlace();
          if (!empty($pubPlace)): ?>
              <span property="location"><?= $this->escapeHtml($pubPlace) ?></span>
          <? endif; ?>
                        <? $pubName = $field->getName();
                        if (!empty($pubName)): ?>
                            <span property="name"><?= $this->escapeHtml($pubName) ?></span>
                        <? endif; ?>
          </span>
                    <? $pubDate = $field->getDate();
                    if (!empty($pubDate)): ?>
                        <span property="publicationDate"><?= $this->escapeHtml($pubDate) ?></span>
                    <? endif; ?>
                    <br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

<? /*
    <!-- Ausgabe -->
    <? $seriesNr = $this->driver->getSeriesNr();
    if ($seriesNr): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Series Number') ?>:</th>
            <td>
                <span property="seriesNumber"><?= $this->escapeHtml($seriesNr) ?></span>
            </td>
        </tr>
    <? endif; ?>
*/ ?>

    <!-- Schriftenreihe -->
    <? /* Display series section if at least one series exists. */ ?>
    <? $series = $this->driver->getSeries();
    if (!empty($series)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Series') ?>:</th>
            <td>
                <? foreach ($series as $field): ?>
                    <? /* Depending on the record driver, $field may either be an array with
             "name" and "number" keys or a flat string containing only the series
             name.  We should account for both cases to maximize compatibility. */
                    ?>
                    <? if (is_array($field)): ?>
                        <? if (!empty($field['name'])): ?>
                            <a href="<?= $this->record($this->driver)->getLink('series', $field['name']) ?>"><?= $this->escapeHtml($field['name']) ?></a>
                            <? if (!empty($field['number'])): ?>
                                <?= $this->escapeHtml($field['number']) ?>
                            <? endif; ?>
                            <br/>
                        <? endif; ?>
                    <? else: ?>
                        <a href="<?= $this->record($this->driver)->getLink('series', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                        <br/>
                    <? endif; ?>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <!-- Schlagworte -->
    <? $subjects = $this->driver->getAllSubjectHeadings();
    if (!empty($subjects)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Subjects') ?>:</th>
            <td>
                <? $line = 0;
                foreach ($subjects as $field): ?>
                    <div class="subjectLine <?= ++$line > 5 ? 'hide more' : '' ?>" property="keywords">
                        <? $subject = ''; ?>
                        <? $i = 0;
                        foreach ($field as $subfield): ?>
                            <?= ($i++ == 0) ? '' : ' &gt; ' ?>
                            <? $subject = trim($subject . ' ' . $subfield); ?>
                            <a title="<?= $this->escapeHtml($subject) ?>"
                               href="<?= $this->record($this->driver)->getLink('subject', $subject) ?>"
                               class="subjectHeading"><?= $this->escapeHtml($subfield) ?></a>
                        <? endforeach; ?>
                    </div>
                <? endforeach; ?>
                <? if (count($subjects) > 5): ?>
                <div>
                    <a id="showAllTopics" title="More" class="add" onclick="$('.subjectLine.more, #showAllTopics, #hideTooManyTopics').toggle(); return false;" href="#">More</a>
                    <a id="hideTooManyTopics" title="Less" class="add hide" onclick="$('.subjectLine.more,  #showAllTopics, #hideTooManyTopics').toggle(); return false;" href="#">Less</a>
                </div>
                <? endif; ?>
            </td>
        </tr>
    <? endif; ?>

    <!-- TranslatedTerms -->
    <? $subjects = $this->driver->getAllSubjectHeadings();
    if (!empty($subjects)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('TranslatedTerms') ?>:</th>
            <td>
                <? $line = 0;
                foreach ($subjects as $field): ?>
                    <div class="subjectLine <?= ++$line > 5 ? 'hide more' : '' ?>" property="keywords">
                        <? $subject = ''; ?>
                        <? $i = 0;
                        foreach ($field as $subfield): ?>
                            <?= ($i++ == 0) ? '' : ' &gt; ' ?>
                            <? $subject = trim($subject . ' ' . $subfield); ?>
                            <a title="<?= $this->escapeHtml($subject) ?>"
                               href="<?= $this->record($this->driver)->getLink('subject', $subject) ?>"
                               class="subjectHeading"><?= $this->escapeHtml($subfield) ?></a>
                        <? endforeach; ?>
                    </div>
                <? endforeach; ?>
                <? if (count($subjects) > 5): ?>
                <div>
                    <a id="showAllTopics" title="More" class="add" onclick="$('.subjectLine.more, #showAllTopics, #hideTooManyTopics').toggle(); return false;" href="#">More</a>
                    <a id="hideTooManyTopics" title="Less" class="add hide" onclick="$('.subjectLine.more,  #showAllTopics, #hideTooManyTopics').toggle(); return false;" href="#">Less</a>
                </div>
                <? endif; ?>
            </td>
        </tr>
    <? endif; ?>

    <!-- Mini Kontext -->
    <? $belongsTo = $this->driver->getBelongsTo();
    if (!empty($belongsTo)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Belongs to') ?>:</th>
            <td>
                <a href="<?= $this->url('record') . $belongsTo[0] ?>"><?= $belongsTo[1] ?></a>
            </td>
        </tr>
    <? endif; ?>

    <? $belongsToTop = $this->driver->getBelongsToTop();
    if (!empty($belongsToTop)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Belongs to') ?>:</th>
            <td>
                <a href="<?= $this->url('record') . $belongsToTop[0] ?>"><?= $belongsToTop[1] ?></a>
            </td>
        </tr>
    <? endif; ?>


    <!-- tags -->
    <? $tagList = $this->driver->getTags(); ?>
    <tr valign="top">
        <th><?= $this->transEsc('Tags') ?>:</th>
        <td>
        <span style="float:right;">
          <a href="<?= $this->recordLink()->getActionUrl($this->driver, 'AddTag') ?>"
             class="tool add tagRecord controller<?= $this->record($this->driver)->getController() ?>"
             title="<?= $this->transEsc('Add Tag') ?>" id="tagRecord"><?= $this->transEsc('Add Tag') ?></a>
        </span>

            <div id="tagList">
                <? if (count($tagList) > 0): ?>
                    <? $i = 0;
                    foreach ($tagList as $tag): ?><?=
                        ($i++ == 0) ? '' : ', ' ?><a
                        href="<?= $this->url('tag-home') ?>?lookfor=<?= urlencode($tag->tag) ?>"><?= $this->escapeHtml($tag->tag) ?></a> (<?= $this->escapeHtml($tag->cnt) ?>)<? endforeach; ?>
                <? else: ?>
                    <?= $this->transEsc('No Tags') ?>, <?= $this->transEsc('Be the first to tag this record') ?>!
                <? endif; ?>
            </div>
        </td>
    </tr>


    <? $recordLinks = $this->driver->getAllRecordLinks();
    if (!empty($recordLinks)): ?>
        <tr valign="top">
            <th><?= $this->transEsc('Related Items') ?></th>
            <td>
                <? foreach ($recordLinks as $recordLink): ?>
                    <?= $this->transEsc($recordLink['title']) ?>:
                    <a href="<?= $this->recordLink()->related($recordLink['link']) ?>"><?= $this->escapeHtml($recordLink['value']) ?></a>
                    <br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>
</table>
<? /* End Main Details */ ?>
</div>

<div class="span-4 last">
    <? /* Display thumbnail if appropriate: */ ?>
    <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium');
    $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
    <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?= $this->escapeHtml($largeThumb) ?>"><? endif; ?>
        <img alt="<?= $this->transEsc('Cover Image') ?>" class="recordcover"
             src="<?= $this->escapeHtml($mediumThumb); ?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
    <? else: ?>
        <img src="<?= $this->url('cover-unavailable') ?>" class="recordcover"
             alt="<?= $this->transEsc('No Cover Image') ?>"/>
    <? endif; ?>

    <? /* Display qrcode if appropriate: */ ?>
    <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
    <? if ($QRCode): ?>
        <img alt="<?= $this->transEsc('QR Code') ?>" class="qrcode" src="<?= $this->escapeHtml($QRCode); ?>"/>
    <? endif; ?>

    <? /* Display the lists that this record is saved to */ ?>
    <div class="savedLists info hide" id="savedLists">
        <strong><?= $this->transEsc("Saved in") ?>:</strong>
    </div>

    <?= $this->record($this->driver)->getPreviews() ?>
</div>

<div class="clear"></div>
