<?
/**
 * THIS IS HOW TO MAKE THIS PAGE THE DEFAULT (landing) PAGE
 *
 * 1. Open "/vufind2/config/vufind/config.ini".
 * 2. Replace the value of "defaultModule" with "Search".
 * 3. When calling "/vufind/Index" in the browser, this page should be shown.
 */

// Set page title.
$this->headTitle($this->translate('Home'));

// Distribute institutions to 3 arrays which can be used to populate 3 columns
$institutionsCols = $this->distributeToArrays($institutions, array(6, 7, 99));

?>
<div id="topicsPage">
    <div class="missionStatement col-sm-12">
        <h1><?= $this->transEsc('Mission statement') ?></h1>
    </div>
    <div class="col-sm-8">
        <h2><?= $this->transEsc('Participating institutions'); ?></h2>
        <div>
            <!-- Start google maps -->
            <div id="topic-map-canvas"></div>
            <script src="https://maps.googleapis.com/maps/api/js?language=de"></script>
            <script>
                (function(){
                    var marker, i, infoWindow, locations, map, url;
                    infoWindow = new google.maps.InfoWindow();
                    locations = [
                        <?php for ($i = 0; $i < count($institutions); $i++) : ?>
                            [
                                <? $institution = $institutions[$i]; ?>
                                <?= json_encode($institution['name']); ?>,
                                <?= (float) $institution['latitude']; ?>,
                                <?= (float) $institution['longitude']; ?>,
                                <?= json_encode($institution['id']); ?>,
                                <?= json_encode($institution['address']); ?>
                            ]
                            <?php if ($i != count($institutions) - 1) : ?>,<?php endif; ?>
                        <?php endfor; ?>
                    ];
                    map = new google.maps.Map(document.getElementById('topic-map-canvas'), {
                        zoom: 4,
                        center: new google.maps.LatLng(51.1656910, 10.4515260),
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    });
                    for (i = 0; i < locations.length; i++) {
                        marker = new google.maps.Marker({
                            position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                            map: map,
                            icon: '<?= $this->url('home') . "themes/meta-bootstrap3/images/marker.png"; ?>'
                        });
                        google.maps.event.addListener(marker, 'click', (function(marker, i) {
                            return function() {
                                url = '<?= $this->url('search-results'); ?>?limit=20&filter[]=institution%3A' + locations[i][3];
                                infoWindow.setContent(
                                    '<strong>' + locations[i][0] + '</strong><br />' +
                                    locations[i][4] + '<br />' +
                                    '<a href="' + url + '" style="text-decoration: underline">' +
                                    '<?= $this->translate('See the inventory') ?>'
                                    +'</a>'
                                );
                                infoWindow.open(map, marker);
                            }
                        })(marker, i));
                    }
                })();
            </script>
            <!-- END google maps -->
        </div>
    </div>
    <div class="col-sm-4">
        <h2><?= $this->transEsc('Inventory by document types'); ?>:</h2>
        <ul id="inventoryFacet">
            <?php foreach ($inventoryFacet as $entry) : ?>
                <li>
                    <div class="format">
                        <a href="<?= $this->url('search-results'); ?>?limit=20&filter[]=format%3A<?= urlencode($entry['value']); ?>">
                            <?= $entry['displayText']; ?>
                        </a>
                        <span class="count">
                            (<?= number_format($entry['count'], 0, ',', '.'); ?>)
                        </span>
                    </div>
                    <div class="barWrapper">
                        <div class="bar" style="background-color: <?= $entry['color']; ?>; width: <?= max(1, $entry['percent']); ?>%"></div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="col-sm-12" id="institutionList">
        <h2><?= $this->transEsc('Inventory of the institutions'); ?></h2>
        <div class="body">
            <?php $lastCountry = ""; ?>
            <?php foreach ($institutionsCols as $column) : ?>
                <div class="col-sm-4">
                    <?php foreach ($column as $institution) : ?>
                        <?php if ($lastCountry !== $institution["country"]) : ?>
                            <?php $lastCountry = $institution["country"]; ?>
                            <h3><?= $this->transEsc($institution["country"]); ?></h3>
                        <?php endif; ?>
                        <div class="institution">
                            <a href="<?= $this->url('search-results'); ?>?limit=20&filter[]=institution%3A<?= urlencode($institution["id"]); ?>">
                                <?= $institution["name"]; ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-sm-8">
        <h2 data-section-toggle><?= $this->transEsc('Theme overview'); ?>:</h2>
        <ul class="body tag_cloud">
            <? foreach ($topics as $topic): ?>
                <li>
                    <a title="<?= $topic['count'] ?> <?= $this->translate('Documents') ?>" class="w<?= $topic['weight'] ?>"
                        href="<?= $this->record($this->solrDriver)->getLink('subject', $topic['value']) ?>"><?= $topic['displayText'] ?></a>
                </li>
            <? endforeach; ?>
        </ul>
    </div>
    <div class="col-sm-4">
        <h2 data-section-toggle="true"><?= $this->transEsc('Perhaps interesting?'); ?></h2>
        <ul class="body" id="randomBooks">
            <?php foreach ($this->randomBooks as $book) : ?>
                <?php $this->driver = $book; // Make "result-list.phtml" template reusable ?>
                <li class="result row">
                    <? include dirname(__DIR__) . "/RecordDriver/SolrIDA/result-list.phtml"; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>