<?
/**
 * THIS IS HOW TO MAKE THIS PAGE THE DEFAULT (landing) PAGE
 *
 * 1. Open "/vufind2/config/vufind/config.ini".
 * 2. Replace the value of "defaultModule" with "Search".
 * 3. When calling "/vufind/Index" in the browser, this page should be shown.
 */

// Set page title.
$this->headTitle($this->translate('Home'));
$rowOneInstitutionCount = 15;
?>
<div id="topicsPage">
    <div class="missionStatement col-md-12">
        <h1><?= $this->transEsc('Mission statement') ?></h1>
    </div>
    <div class="col-md-8">
        <h2><?= $this->transEsc('Participating institutions'); ?></h2>
        <div>
            MAP
        </div>
    </div>
    <div class="col-md-4">
        <h2><?= $this->transEsc('Inventory by document types'); ?>:</h2>
        <ul id="inventoryFacet">
            <?php foreach ($inventoryFacet as $entry) : ?>
                <li>
                    <div class="format">
                        <?= $entry['displayText']; ?>
                        <span class="count">
                            (<?= number_format($entry['count'], 0, ',', '.'); ?>)
                        </span>
                    </div>
                    <div class="barWrapper">
                        <div class="bar" style="background-color: <?= $entry['color']; ?>; width: <?= max(1, $entry['percent']); ?>%"></div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="col-md-12" id="institutionList">
        <h2><?= $this->transEsc('Inventory of the institutions'); ?></h2>
        <div class="body">
            <?php  ?>
            <div class="col-md-4">
                <h3><?= $this->transEsc('Germany'); ?></h3>
                <ul>
                    <?php for ($i = 0; $i < $rowOneInstitutionCount; $i++) : ?>
                        <li><a href=""><?= $institutions["Germany"][$i]; ?></a></li>
                    <?php endfor; ?>
                </ul>
            </div>
            <div class="col-md-4">
                <ul>
                    <?php for ($i = $rowOneInstitutionCount; $i < count($institutions["Germany"]); $i++) : ?>
                        <li><a href=""><?= $institutions["Germany"][$i]; ?></a></li>
                    <?php endfor; ?>
                </ul>
            </div>
            <div class="col-md-4">
                <?php foreach ($institutions as $country => $institutionsInCountry) : ?>
                    <?if ("Germany" == $country) continue; ?>
                    <h3><?= $this->transEsc($country); ?></h3>
                    <ul>
                        <?php foreach ($institutionsInCountry as $institutionName) : ?>
                            <li><a href=""><?= $institutionName; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <h2><?= $this->transEsc('Theme overview'); ?>:</h2>
        <ul class="body tag_cloud">
            <? foreach ($topics as $topic): ?>
                <li>
                    <a title="<?= $topic['count'] ?> <?= $this->translate('Documents') ?>" class="w<?= $topic['weight'] ?>"
                        href="<?= $this->record($this->driver)->getLink('subject', $topic['value']) ?>"><?= $topic['displayText'] ?></a>
                </li>
            <? endforeach; ?>
        </ul>
    </div>
    <div class="body col-md-4">
        <h2><?= $this->transEsc('Perhaps interesting?'); ?></h2>
        <div class="body">
            BOOKS
        </div>
    </div>
</div>