<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->localizedNumber($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . $this->localizedNumber($this->scrollData['resultTotal']) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<?php /*PHE not required
<?=$this->record($this->driver)->getToolbar()?>
*/ ?>

<div class="col-md-9">
  <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>
  </div>

  <?php /* PHE Building tabs is not required. Echoing them directly below
  <? if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <ul class="recordTabs nav nav-tabs">
      <? foreach ($this->tabs as $tab => $obj): ?>
      <? // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
        if ($isCurrent) {
          $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
          $activeTabObj = $obj;
        }
        $tab_classes = array();
        if ($isCurrent) $tab_classes[] = 'active';
        if (!$obj->isVisible()) $tab_classes[] = 'hidden';
      ?>
      <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
        <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
    </ul>
  <? endif; ?>

  <div class="tab-content" id="record-tabs">
    <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
      <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
    </div>
  </div>

  <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
  */ ?>

  <div class="record row detail-view-detail-row">
    <?php $tabCount = 0; ?>
    <?php foreach (array_reverse($this->tabs) as $tab => $obj): ?>
      <div class="col-sm-6">
        <?php if ($tab == "Details") : ?>
          <h4><?php echo $this->transEsc('Description'); ?></h4>
        <?php elseif ($tab == "HierarchyTree") : ?>
          <h4><?php echo $this->transEsc('Context'); ?></h4>
        <?php endif; ?>
        <?php echo $this->record($this->driver)->getTab($obj)?>
      </div>
      <?php $tabCount++; ?>
    <?php endforeach; ?>

    <?php /* PHE - START of the institution details */ ?>
    <?php $institution = reset($this->driver->getInstitutions()) ?>
    <?php $institutionDetails = $this->driver->getInstitutionDetails($institution); ?>
    <?php if ($institutionDetails != NULL) : ?>
      <?php /* PHE - start next row, if previous row is full */ ?>
      <?php if ($tabCount == 2) : ?>
        </div><div class="record row detail-view-detail-row">
      <? endif; ?>
      <div class="col-sm-6 institution">
        <h4><?php echo $this->transEsc('Institution'); ?></h4>
        <h5><?= $this->escapeHtmlAttr($institution); ?></h5>
        <?php if (isset($institutionDetails["address"])) : ?>
          <div id="institution-address"><?= strip_tags($institutionDetails["address"], '<br><strong>'); ?></div>
        <?php endif; ?>
        <?php if (isset($institutionDetails["addressExtra"])) : ?>
          <div class="address-extra"><?= strip_tags($institutionDetails["addressExtra"], '<br><strong>'); ?></div>
        <?php endif; ?>
        <?php if (isset($institutionDetails["openingHours"])) : ?>
          <div class="opening-hours"><?= strip_tags($institutionDetails["openingHours"], '<br><strong>'); ?></div>
        <?php endif; ?>
      </div>
    <?php endif; ?>
    <?php /* PHE - END of the institution details */ ?>

  </div>
</div>

<div class="sidebar col-md-3 hidden-print detail-view-sidebar">
  <?php foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <?php endforeach; ?>
</div>
