<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");

// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();

// Get institution details
$institution = reset($this->driver->getInstitutions());
$userLanguage = $this->plugin('translate')->getTranslator()->getLocale();
$institutionDetails = $this->driver->getInstitutionDetails($institution, $userLanguage);

?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<?php /*PHE not required
<?=$this->record($this->driver)->getToolbar()?>
*/ ?>

<div class="col-md-9">
    <div class="record recordId source<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" id="record">
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId" id="record_id"/>
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource"/>
        <?= $this->flashmessages() ?>
        <?= $this->record($this->driver)->getCoreMetadata() ?>
    </div>

    <?php /* PHE Building tabs is not required. Echoing them directly below
      <? if (count($this->tabs) > 0): ?>
        <a name="tabnav"></a>
        <ul class="recordTabs nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>
          <? // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
            if ($isCurrent) {
              $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
              $activeTabObj = $obj;
            }
          ?>
        <li<?=$isCurrent ? ' class="active"' : ''?>>
            <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
          </li>
          <? endforeach; ?>
        </ul>
      <? endif; ?>

      <div class="tab-content" id="record-tabs">
        <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
          <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
        </div>
      </div>

      <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
    */ ?>

    <div class="record row detail-view-detail-row">
        <?php $tabCount = 0; ?>
        <?php foreach (array_reverse($this->tabs) as $tab => $obj): ?>
            <div class="col-sm-6">
                <?php if ($tab == "Details") : ?>
                    <h4 data-toggle="collapse" id="tabnav"><?php echo $this->transEsc('further information'); ?></h4>
                <?php elseif ($tab == "HierarchyTree") : ?>
                    <h4 data-toggle="collapse"><?php echo $this->transEsc('Context'); ?></h4>
                <?php endif; ?>
                <div class="collapsible">
                    <?php echo $this->record($this->driver)->getTab($obj) ?>
                </div>
            </div>
            <?php $tabCount++; ?>
        <?php endforeach; ?>

    <?php /* PHE - START start next row, if previous row is full */ ?>
    <?php if ($institutionDetails != NULL && $tabCount > 1 && $tabCount % 2 == 0) : ?>
    </div><div class="record row detail-view-detail-row">
    <? endif; ?>
    <?php /* PHE - END start next row, if previous row is full */ ?>
        <?php /* PHE - START of the institution details */ ?>
        <?php if ($institutionDetails != NULL) : ?>
            <div class="col-sm-6 institution detail-view-detail-row">
                <h4 data-toggle="collapse">
                    <?php echo $this->transEsc('Institution'); ?>
                </h4>
                <div class="collapsible">
                    <h5><?= $this->escapeHtml($institution); ?></h5>
                    <?php if (isset($institutionDetails["address"])) : ?>
                        <div id="institution-address"><?= strip_tags($institutionDetails["address"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["addressExtra"])) : ?>
                        <div class="address-extra"><?= strip_tags($institutionDetails["addressExtra"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["openingHours"])) : ?>
                        <div class="opening-hours"><?= strip_tags($institutionDetails["openingHours"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <!-- Start google maps -->
                    <?php if (isset($institutionDetails["address"])) : ?>
                        <div id="map-canvas"></div>
                        <script src="https://maps.googleapis.com/maps/api/js?language=de"></script>
                        <script>
                            google.maps.event.addDomListener(window, 'load', function () {
                                var mapOptions = {zoom: 15};
                                var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
                                var address = <?= json_encode(strip_tags($institutionDetails["address"], "<br>")); ?>.replace("<br>", ", ");
                                geocoder = new google.maps.Geocoder();
                                geocoder.geocode({'address': address}, function (results, status) {
                                    if (status == google.maps.GeocoderStatus.OK) {
                                        map.setCenter(results[0].geometry.location);
                                        new google.maps.InfoWindow({
                                            map: map,
                                            position: results[0].geometry.location,
                                            content: "<strong><?= str_replace('"', '\"', $this->escapeHtml($institution)); ?></strong><br />" + address
                                        });
                                    }
                                });
                            });
                        </script>
                    <?php endif; ?>
                    <!-- END google maps -->
                </div>
            </div>
        <?php endif; ?>
        <?php /* PHE - END of the institution details */ ?>
    </div>
</div>

<div class="sidebar col-md-3 hidden-print detail-view-sidebar">
    <?php foreach ($this->related()->getList($this->driver) as $current): ?>
        <?= $this->related()->render($current) ?>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    // Allow search result section toggling
    $(document).ready(function () {
        var maxMobileWidth = 768; // px
        var headlines = $(".detail-view-detail-row h4[data-toggle], .detail-view-sidebar h4");
        var sections = $(".detail-view-detail-row .collapsible, .detail-view-sidebar ul");
        // Hide sections on mobile devices
        $(window).bind("load resize", function (e) {
            ($(document).width() <= maxMobileWidth) ? sections.hide() : sections.show();
            headlines.removeClass("open");
        });
        // Make sections toggleable on mobile devices
        headlines.click(function () {
            if (($(document).width() <= maxMobileWidth)) {
                var $this = $(this);
                $this.next().slideToggle("normal", function (e) {
                    $this.toggleClass("open");
                });
            }
        });
    });
</script>