<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");

// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();

// Get institution details
$institution = reset($this->driver->getInstitutions());
$userLanguage = $this->plugin('translate')->getTranslator()->getLocale();
$institutionDetails = $this->driver->getInstitutionDetails($institution, $userLanguage);

?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<?php /*PHE not required
<?=$this->record($this->driver)->getToolbar()?>
*/ ?>
<div class="col-md-9">
    <div class="record recordId source<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" id="record">
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId" id="record_id"/>
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource"/>
        <?= $this->flashmessages() ?>
        <?= $this->record($this->driver)->getCoreMetadata() ?>
    </div>

    <?php /* PHE Building tabs is not required. Echoing them directly below
      <? if (count($this->tabs) > 0): ?>
        <a name="tabnav"></a>
        <ul class="recordTabs nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>
          <? // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
            if ($isCurrent) {
              $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
              $activeTabObj = $obj;
            }
          ?>
        <li<?=$isCurrent ? ' class="active"' : ''?>>
            <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
          </li>
          <? endforeach; ?>
        </ul>
      <? endif; ?>

      <div class="tab-content" id="record-tabs">
        <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
          <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
        </div>
      </div>

      <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
    */ ?>

      <div class="record row detail-view-detail-row">
        <?php $tabCount = 0; ?>
        <?php foreach ($this->tabs as $tab => $obj): ?>
            <div class="col-sm-6">
                <?php if ($tab == "Description") : ?>
                    <h4 data-section-toggle="true" id="tabnav"><?php echo $this->transEsc('further information'); ?></h4>
                <?php elseif ($tab == "HierarchyTree") : ?>
                    <h4 data-section-toggle="true"><?php echo $this->transEsc('Context'); ?></h4>
                <?php elseif ($tab == "OtherInstitutions") : ?>
                	<h4 data-section-toggle="true"><?php echo $this->transEsc('Also available in other institutions'); ?></h4>
                <?php endif; ?>
                <div class="collapsible">
                    <?php echo $this->record($this->driver)->getTab($obj) ?>
                </div>
            </div>
            <?php $tabCount++; ?>
        <?php endforeach; ?>

    <?php /* PHE - START start next row, if previous row is full */ ?>
    <?php if ($institutionDetails != NULL && $tabCount > 1 && $tabCount % 2 == 0) : ?>
    </div><div class="record row detail-view-detail-row">
    <? endif; ?>
    <?php /* PHE - END start next row, if previous row is full */ ?>
        <?php /* PHE - START of the institution details */ ?>
        <?php if ($institutionDetails != NULL) : ?>
            <?php $institutionName = isset($institutionDetails["name"]) ? $institutionDetails["name"] : $institution; ?>
            <div class="col-sm-6 institution detail-view-detail-row">
                <h4 data-section-toggle="true" data-toggle-yyy="mapyyy">
		    <a name="link"></a>
                    <?php echo $this->transEsc('Location'); ?>
                </h4>
                <div class="collapsible">
                    <h5><?= strip_tags($institutionName, "<br>"); ?></h5>
                    <?php if (isset($institutionDetails["address"])) : ?>
                        <div id="institution-address"><?= strip_tags($institutionDetails["address"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["addressExtra"])) : ?>
                        <div class="address-extra"><?= strip_tags($institutionDetails["addressExtra"], '<br><strong><a>'); ?>&nbsp;<i class="fa fa-external-link"></i><br /><br /></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["openingHours"])) : ?>
                        <div class="opening-hours"><?= strip_tags($institutionDetails["openingHours"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <!-- Start google maps -->
                    <?php if (isset($institutionDetails["address"])) : ?>
                        <div id="map-canvas"></div>
                        <script src="https://maps.googleapis.com/maps/api/js?language=de"></script>
                        <script>
                            (function($) {

                                var map,
                                    lat = <?= (float) $institutionDetails["latitude"]; ?>,
                                    lng = <?= (float) $institutionDetails["longitude"]; ?>;

                                $(function () {

                                    // "Refresh" map after slide down (mobile devices)
                                    $('#map-canvas')
                                        .parents('.collapsible')
                                        // Custom event
                                        .on('afterSlideDown', function () {

                                            // Repaint map
                                            google.maps.event.trigger(map, 'resize');

                                            // Re-center map
                                            map.setCenter(new google.maps.LatLng(lat, lng));
                                        });
                                });

                                google.maps.event.addDomListener(window, 'load', function () {
                                    var mapOptions = {zoom: 14, zoomControlOptions: { position: google.maps.ControlPosition.LEFT_BOTTOM }};
                                    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

                                    var address = <?= json_encode(strip_tags($institutionDetails["address"], "<br>")); ?>.replace("<br>", ", ");
                                    map.setCenter(new google.maps.LatLng(lat, lng));
                                    var marker = new google.maps.Marker({
                                        position: new google.maps.LatLng(lat, lng),
                                        map: map,
                                        icon: '<?= $this->url('home') . "themes/meta-bootstrap3/images/marker.png"; ?>'
                                    });

                                    // Register click on marker
                                    google.maps.event.addListener(marker, 'click', function() {
                                        window.open('https://www.google.com/maps?q=' + lat + ',' + lng);
                                    });
                                });
                            })(jQuery);
                        </script>
                    <?php endif; ?>
                    <!-- END google maps -->
                </div>
            </div>
        <?php endif; ?>
        <?php /* PHE - END of the institution details */ ?>
        
        
      
        
        
    </div>
    
    
    
    
</div>

<div class="sidebar col-md-3 hidden-print detail-view-sidebar" data-sidebar-toggle="true">
    <?php foreach ($this->related()->getList($this->driver) as $current): ?>
        <?= $this->related()->render($current) ?>
    <?php endforeach; ?>
</div>
