<? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
  <div class="mobileViewLink"><a href="<?=$this->escapeHtmlAttr($mobileViewLink)?>" class="btn btn-primary btn-lg"><?=$this->transEsc("mobile_link")?></a></div>
<? endif; ?>
<div class="col-sm-12"><div class="footer-brand">METADATEN-<br />KATALOG | * Release Candidate</div></div>
<div class="col-sm-3"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
<ul>
  <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
  <li><a href="<?=$this->url('topics/topics')?>"><?=$this->transEsc('Tagcloud of Subjects')?></a></li>
<?php /* PHE not required
  <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
  <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
 */ ?>
</ul>
</div>
<div class="col-sm-3"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
        <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
<?php /* PHE not required
        <li><a href="#"><?=$this->transEsc('Ask a Librarian')?></a></li>
        <li><a href="#"><?=$this->transEsc('FAQs')?></a></li>
*/ ?>
    </ul>
</div>
<div class="col-sm-3"><p><strong><?=$this->transEsc('Service')?></strong></p>
<ul>
  <li><a href="mailto:metaprojektr@ida-dachverband.de?subject=[Anfrage META]"><?=$this->transEsc('Contact')?></a></li>
  <li><a href="http://www.ida-dachverband.de/impressum/"><?=$this->transEsc('Imprint')?></a></li>
  <li><a href="http://www.ida-dachverband.de/"><?=$this->transEsc('Website')?></a></li>
</ul>
</div>
<div class="col-sm-3">
    <p class="sponsored"><?=$this->transEsc('Sponsored by')?>:</p>
    <?php $bmfTitle ="Bundesministerium für Familie, Senioren, Frauen und Jugend"; ?>
    <img class="sponsorLogo" title="<?= $bmfTitle; ?>" alt="<?= $bmfTitle; ?>" src="<?= $this->imageLink("bmfsfj-logo.png");?>" />
</div>

