<div class="span-13" vocab="http://schema.org/" resource="#record"
     typeof="<?= $this->driver->getSchemaOrgFormats() ?> Product">


    <!-- Format -->
    <? $formats = $this->driver->getFormats();
    if (!empty($formats)): ?>
        <div><?= $this->record($this->driver)->getFormatList() ?></div>
    <? endif; ?>
    <!-- Title -->
    <? $shortTitle = $this->driver->getShortTitle(); ?>
    <? $titleSub = $this->driver->getTitleSub(); ?>
    <h1 property="name"><b><?= $this->escapeHtml($shortTitle); ?></b>
        <?= isset($titleSub) && $titleSub != '' ?  " : " . $this->escapeHtml($titleSub) : ""; ?></h1>



<!-- Include details -->
<? include(dirname(__FILE__).'/../../RecordTab/description-content.phtml'); ?>

</div>

<div class="span-4 last">
    <? /* Display thumbnail if appropriate: */ ?>
    <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium');
    $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
    <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?= $this->escapeHtml($largeThumb) ?>"><? endif; ?>
        <img alt="<?= $this->transEsc('Cover Image') ?>" class="recordcover"
             src="<?= $this->escapeHtml($mediumThumb); ?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
    <? else: ?>
        <img src="<?= $this->url('cover-unavailable') ?>" class="recordcover"
             alt="<?= $this->transEsc('No Cover Image') ?>"/>
    <? endif; ?>

    <? $isbn = $this->driver->getCleanISBN() ?>
    <? $amazonassociate = $this->driver->getAmazonAffiliateId() ?>
    <? if ($isbn && $amazonassociate): ?>
        <a href="http://www.amazon.de/gp/product/<?= $isbn ?>?tag=<?= $amazonassociate ?>" target="_blank" title="<?= $this->transEsc('Buy from Amazon') ?>"><?=$this->transEsc('Amazon')?><img src="<?= $this->imageLink('icons/amazon_16.png') ?>"/></a>
    <? endif; ?>
    <? if (count($this->driver->getCitationFormats()) > 0): ?>
        <? $controllerClass = 'controller' . $this->record($this->driver)->getController(); ?>
        <br/><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" class="citeRecord cite <?=$controllerClass?>" id="share" title="<?=$this->transEsc('Share')?>"><?=$this->transEsc('Share this')?></a>
    <? endif; ?>

    <? /* Display the lists that this record is saved to */ ?>
    <div class="savedLists info hide" id="savedLists">
        <strong><?= $this->transEsc("Saved in") ?>:</strong>
    </div>

    <?= $this->record($this->driver)->getPreviews() ?>
</div>

<div class="clear"></div>
