<div id="fb-root"></div>
<?
    // Set page title.
    $this->headTitle($this->translate('Record Citations'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('Record Citations') . '</em>';

    // Collect citation data:
    $helper = $this->citation($this->driver);
    $citations = array();
    foreach ($this->driver->getCitationFormats() as $format) {
        $citations[$format . ' Citation'] = $helper->getCitation($format);
    }
?>
<? if (count($citations) == 0): ?>
  <?=$this->transEsc('No citations are available for this record')?>
<? else: ?>
  <? foreach ($citations as $caption => $citation): ?>
    <? $plainCitation = $this->escapeHtml(strip_tags($citation)); ?>
    <strong><?=$this->transEsc($caption)?></strong>
    <p class="citationText">
      <?=$citation?>
        <? // Mail ?>
        <a href="mailto: ?subject=<?= $this->escapeHtml($this->driver->getDisplayTitle()); ?>&body=<?= $plainCitation ?>">Mail</a>
        <? // Clipboard ?>
        <button class="copy-button" data-clipboard-text="<?= $plainCitation ?>" title="Click to copy me.">Copy to Clipboard</button>
        <? // Twitter ?>
        <a href="https://twitter.com/intent/tweet?button_hashtag=Genderbib&text=<?= $plainCitation ?>" target="_blank" class="twitter-hashtag-button">Tweet</a>
        <? // Facebook ?>
        <a href="https://www.facebook.com/sharer/sharer.php?u=<?= $this->url('record') . $this->driver->getUniqueID() ?>" target="_blnak">Facebook</a>
    </p>
  <? endforeach; ?>
  <div class="note"><?=$this->transEsc('Warning: These citations may not always be 100% accurate')?>.</div>
  <script>var client = new ZeroClipboard($(".copy-button"));</script>
<? endif; ?>