<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?=$this->layout()->userLang?>" xml:lang="en">
<head>
    <?$this->headThemeResources()?>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
    // Set up OpenSearch link:
    $this->headLink(
        array(
            'href' => $this->url('search-opensearch') . '?method=describe',
            'type' => 'application/opensearchdescription+xml',
            'title' => $this->transEsc('Library Catalog Search'),
            'rel' => 'search'
        )
    );
    ?>
    <?
    $feedback = $this->feedback()->tabEnabled();
    if ($feedback) {
        $this->headLink()->appendStylesheet('ie8-tab.css', 'screen, projection', 'IE 8');
    }
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
    // Set global path for Javascript code:
    $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

    $this->jsTranslations()->addStrings(
        array(
            'loading'=>'Loading'
        )
    );
    // Deal with cart stuff:
    if (!isset($this->renderingError)) {
        $cart = $this->cart();
        if ($cart->isActive()) {
            $this->headScript()->appendFile("jquery.cookie.js");
            $this->headScript()->appendFile("cart.js");
            $this->jsTranslations()->addStrings(
                array(
                    'bulk_noitems_advice' => 'bulk_noitems_advice',
                    'confirmEmpty' => 'bookbag_confirm_empty',
                    'viewBookBag' => 'View Book Bag',
                    'addBookBag' => 'Add to Book Bag',
                    'removeBookBag' => 'Remove from Book Bag',
                    'itemsAddBag' => 'items_added_to_bookbag',
                    'itemsInBag' => 'items_already_in_bookbag',
                    'bookbagMax' => $cart->getMaxSize(),
                    'bookbagFull' => 'bookbag_full_msg',
                    'bookbagStatusFull' => 'bookbag_full',
                )
            );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
    }
    if ($feedback) {
        $this->headScript()->appendFile("jquery.tabSlideOut.v2.0.js");
        $this->headScript()->appendFile("feedback.js");
    }

    // Session keep-alive
    if ($this->KeepAlive()) {
        $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
        $this->headScript()->appendFile("keep_alive.js");
    }
    ?>
    <?=$this->headScript()?>
</head>
<body>
<? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
    <div class="mobileViewLink"><a href="<?=$this->escapeHtml($mobileViewLink)?>"><?=$this->transEsc("mobile_link")?></a></div>
<? endif; ?>
<div class="container">
    <div class="header">
        <?=$this->render('header.phtml')?>
    </div>
    <div class="contentLeft">
        <ul id="mainNav" style="display: none">
            <li class="section-zentrum">
                <a title="" href="https://www.gender.hu-berlin.de/zentrum">
                    <span><?=$this->transEsc("Zentrum")?></span>
                </a>
            </li>
            <li class="section-veranstaltungen">
                <a title="" href="https://www.gender.hu-berlin.de/veranstaltungen">
                    <span><?=$this->transEsc("Veranstaltungen")?></span>
                </a>
            </li>
            <li class="section-studium">
                <a title="" href="https://www.gender.hu-berlin.de/studium">
                    <span><?=$this->transEsc("Studium")?></span>
                </a>
            </li>
            <li class="section-forschung">
                <a title="" href="https://www.gender.hu-berlin.de/forschung">
                    <span><?=$this->transEsc("Forschung")?></span>
                </a>
            </li>
            <li class="section-publikationen">
                <a title="" href="https://www.gender.hu-berlin.de/publikationen">
                    <span><?=$this->transEsc("Publikationen")?></span>
                </a>
            </li>
            <li class="section-internationales">
                <a title="" href="https://www.gender.hu-berlin.de/internationales">
                    <span><?=$this->transEsc("InterNationales")?></span>
                </a>
            </li>
            <li class="section-bibliothek">
                <a title="" href="https://www.gender.hu-berlin.de/bibliothek">
                    <span><?=$this->transEsc("Genderbibliothek")?></span>
                </a>
            </li>
            <li class="section-pcundinternet">
                <a title="" href="https://www.gender.hu-berlin.de/pcundinternet">
                    <span><?=$this->transEsc("PC und Internet")?></span>
                </a>
            </li>
            <li class="section-ztg-blog">
                <a title="" href="http://www2.gender.hu-berlin.de/ztg-blog/">
                    <span><?=$this->transEsc("ZtG-Blog")?></span>
                </a>
            </li>
            <li class="section-links">
                <a title="" href="https://www.gender.hu-berlin.de/links">
                    <span><?=$this->transEsc("Gender_Studies_Links")?></span>
                </a>
            </li>
        </ul>
        <div id="mainNavOpener"></div>
    </div>
    <div class="contentRight">
        <? // Set up the search box -- there are three possible cases:
        // 1. No search box was set; we should default to the normal box
        // 2. It was set to false; we should display nothing
        // 3. It is set to a custom string; we should display the provided version

        // Set up default search box if no data was provided from the template;
        // this covers case 1.  Cases 2 and 3 are then covered by logic below.
        if (!isset($this->layout()->searchbox)) {
            $this->layout()->searchbox = $this->render('search/searchbox.phtml');
        }
        ?>
        <?
        // Set up the feedback tab -- the same possible cases exist as the search box
        if ($feedback && !isset($this->layout()->feedbacktab)) {
            $this->layout()->feedbacktab = $this->render('feedback/email.phtml');
        }
        ?>
        <? if (isset($this->layout()->feedbacktab)): ?>
            <div class="feedbacktab"><?=$this->layout()->feedbacktab?></div>
        <? endif; ?>
        <? if ($this->layout()->breadcrumbs): ?>
            <div class="breadcrumbs">
                <div class="breadcrumbinner">
                    <a href="<?=$this->url('home')?>"><?=$this->transEsc('Home')?></a> <span>&gt;</span>
                    <?=$this->layout()->breadcrumbs?>
                </div>
            </div>
        <? endif; ?>
        <? if ($this->layout()->searchbox !== false): ?>
            <div class="searchbox topSearchBox">
                <?=$this->layout()->searchbox?>
            </div>
        <? endif; ?>
        <div class="main">
            <?=$this->layout()->content?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="footer">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy?>
    </div>
</div>
<?=$this->googleanalytics()?>
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://area51.curie.innermedia.de/projekte/ida/piwik240/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 2]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="http://area51.curie.innermedia.de/projekte/ida/piwik240/piwik.php?idsite=2" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
<script type="text/javascript">
    // IDA search event tracking
    (function ($) {

        function track(c, a) {
            console.log('track:',arguments);
        }

        /**
         * @see http://james.padolsey.com/javascript/parsing-urls-with-the-dom/
         */
        function _parse(url) {
            var a = document.createElement('a');
            a.href = url;
            return {
                source: url,
                protocol: a.protocol.replace(':', ''),
                host: a.hostname,
                port: a.port,
                query: a.search,
                params: (function () {
                    var ret = {},
                        seg = a.search.replace(/^\?/, '').split('&'),
                        len = seg.length, i = 0, s;
                    for (; i < len; i++) {
                        if (!seg[i]) {
                            continue;
                        }
                        s = seg[i].split('=');
                        ret[s[0]] = s[1];
                    }
                    return ret;
                })(),
                file: (a.pathname.match(/\/([^\/?#]+)$/i) || [, ''])[1],
                hash: a.hash.replace('#', ''),
                path: a.pathname.replace(/^([^\/])/, '/$1'),
                relative: (a.href.match(/tps?:\/\/[^\/]+(.+)/) || [, ''])[1],
                segments: a.pathname.replace(/^\//, '').split('/')
            };
        }

        $(function () {

            // Keywords
            $('.authorbox')
                .find('.span-5 a')
                .click(function (e) {
//                    e.preventDefault();//test

                    var tag = $(this).text();

                    if ('string' === typeof tag) {
                        track('Suchergebnisliste', 'Einschränkung mittels Schlagwort "' + tag + '"');
                    }
                });

            // Facets
            $('.sidegroup')
                .find('dl.navmenu a[class^=facet]')
                .click(function (e) {
//                    e.preventDefault();//test

                    var query = $(this).text(),
                        facet = $(this).parents('dl').find('dt').text();
//                    console.log('q=',query,'f=',facet);

                    if ('string' === typeof facet && 'string' === typeof query) {
                        track('Suchergebnisliste', 'Einschränkung mittels Facette "' + facet + '"');
//                        track('Suchergebnisliste', 'Einschränkung mittels Facette "' + facet + '"', 'Kriterium "' + query + '"');
                    }
                });

            // Pagination
            $('.pagination')
                .find('a')
                .click(function (e) {
//                e.preventDefault();//test

                    var pageURL = $(this).attr('href'),
                        pageURLParsed = _parse(pageURL),
                        pageId = pageURLParsed.params.page;

                    if ('string' !== typeof pageId || 0 === pageId.length) {
                        pageId = '1';
                    }

                    track('Suchergebnisliste', 'Wechsel zu Seite ' + pageId);
                });

            // List item
            $('ul.recordSet div[class^=span-] a').click(function (e) {

                var listItem = $(this).parents('li.result'),
                    resultId = (1 === listItem.length && 'string' === typeof listItem.attr('id')) ? listItem.attr('id').replace(/[^0-9]/g ,'') : null;
//                e.preventDefault();//test

                if (null !== resultId && 0 < resultId.length) {
                    track('Suchergebnisliste', 'Auswahl Treffer #' + resultId);
                }
            });
        });
    }) (jQuery);
</script>
</body>
</html>